# Generated by Django 4.1.3 on 2022-11-18 13:25

import advertising.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='cover',
            field=models.ImageField(storage=advertising.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
