# Generated by Django 4.1.3 on 2022-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ad_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='cover',
            field=models.ImageField(upload_to=''),
        ),
    ]
