# Generated by Django 4.1.3 on 2022-11-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ad_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
