# Generated by Django 4.1.3 on 2022-11-19 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ad_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
